### ISSUE TITLE
Sort map by key before printing

### ISSUE THREAD

**Issue by maverickwoo** [k0kubun/pp#23]
I wish there is an option / set of methods that will print maps with keys sorted in a best-effort manner. This can be extremely helpful in diffing outputs across runs.

(As you likely know, spew has a `SortKeys` global config that achieves exactly this.)

Thank you for your consideration.

**Comment by itchyny** [comment]
I think this can be the default behavior as Go 1.12 prints the map in key-sorted way. We can use internal/fmtsort package to make the key order same as the fmt package but to accept that this library should drop support under Go 1.12. I don't like introducing a global option (oops, there's already PrintMapTypes, sigh) because it doesn't work as intended when multiple packages depends on this package. I prefer using internal/fmtsort but supporting versions depend on the author's policy.

**Comment by k0kubun** [comment]
> there's already PrintMapTypes

As the default behavior has been there for a while and there seem to be no user of `PrintMapTypes = false` according to GitHub search, now I'm in favor of reducing the complexity by eliminating the switch as you suggested. Therefore I dropped that now https://github.com/k0kubun/pp/commit/1fdb803f401223aa9a9b7df66b7444d304f50bb0.

> We can use internal/fmtsort package to make the key order same as the fmt package but to accept that this library should drop support under Go 1.12.

Good point. We may want to revisit this after Go 1.11 becomes EOL, unless we have some way to polyfill the package in older versions.

**Comment by deliangyang** [comment]
Maybe be we could create a new branch, which branch named `v3`. if we want to get lower version code, we can do it below.

```bash
go get github.com/k0kubun/pp/v3
```

**Comment by k0kubun** [comment]
> Maybe be we could create a new branch, which branch named v3. if we want to get lower version code, we can do it below.

Done. The following command seems to work, although I think it would require Go 1.11:

```
$ GO111MODULE=on go get github.com/k0kubun/pp/v3
go: extracting github.com/k0kubun/pp/v3 v3.0.5
go: extracting github.com/k0kubun/pp v3.0.1+incompatible
```

I still have no idea why `v3.0.1+incompatible` is shown while v3 branch and v3.0.5 tag seem to support go module.

> We can use internal/fmtsort package to make the key order same as the fmt package

Looks like this is not quite true:

```
printer.go:6:2: use of internal package internal/fmtsort not allowed
```

**Comment by k0kubun** [comment]
> I wish there is an option / set of methods that will print maps with keys sorted in a best-effort manner.
>
> I think this can be the default behavior as Go 1.12 prints the map in key-sorted way. 

Given these inputs, I implemented a patch to sort keys in a best-effort manner: https://github.com/k0kubun/pp/pull/45
