### ISSUE TITLE
disable colors when not output is not a tty

### ISSUE THREAD

**Issue by mtourne** [k0kubun/pp#26]
Colors are great and make the output very readable, however it's a pain when trying to output to a file

go-isatty[1] seems like it would be a good addition to this project to solve this

[1] https://github.com/mattn/go-isatty

**Comment by zelenko** [comment]
Would be nice to have option to disable colors.

**Comment by bigkraig** [comment]
Obviously nicer to have a function that does this, but can't you just do something like this?

```
	pp.SetColorScheme(pp.ColorScheme{
		Bool:            pp.NoColor,
		Integer:         pp.NoColor,
		Float:           pp.NoColor,
		String:          pp.NoColor,
		StringQuotation: pp.NoColor,
		EscapedChar:     pp.NoColor,
		FieldName:       pp.NoColor,
		PointerAdress:   pp.NoColor,
		Nil:             pp.NoColor,
		Time:            pp.NoColor,
		StructName:      pp.NoColor,
		ObjectLength:    pp.NoColor,
	})
```

**Comment by pocari** [comment]
@zelenko @bigkraig 

You can use  `pp.ColoringEnabled = false` .

https://github.com/k0kubun/pp/blob/master/color.go#L72

**Comment by k0kubun** [comment]
Right, thanks for your comment!

**Comment by MakeNowJust** [comment]
@k0kubun Why is `ColoringEnabled` placed as package variable instead of `PrettyPrinter` member? I need to disable coloring of individual `PrettyPrinter`. (Is this question out of scoping of this issue, I wonder. Sorry.)

**Comment by k0kubun** [comment]
`PrettyPrinter` is added very recently https://github.com/k0kubun/pp/commit/45cd6538c9385c466360226ac01e986ddcf7fbe0 and `ColoringEnabled` is a very traditional variable https://github.com/k0kubun/pp/commit/82c68cb300a3cb20a3c9c50a4ed101879e176e3d.

But I see what you mean. Could you try `PrettyPrinter.SetColoringEnabled()` in https://github.com/k0kubun/pp/pull/37? If that's what you want, I'll merge it.
