### ISSUE TITLE
Display of nil slice as same as an empty slice

### ISSUE THREAD

**Issue by xruins** [k0kubun/pp#36]
fmt.Printf with `%#v` displays `[]int{}` for empty int slice, and `[]int(nil)` for nil int slice.
But pp.Printf with `%s` displays `[]int{}` for both of empty int slice and nil int slice.
Is it expected behavior?

# Reproduction
Go Playground: https://play.golang.org/p/M-2JZK--7uW

## Code snippet

``` go
package main

import (
	"fmt"

	"github.com/k0kubun/pp"
)

func main() {
	pp.ColoringEnabled = false

	var nilInts []int
	pp.Printf("pp.Printf: %s\n", nilInts)
	fmt.Printf("fmt.Printf: %#v\n", nilInts)

	emptyInts := []int{}
	pp.Printf("pp.Printf: %s\n", emptyInts)
	fmt.Printf("fmt.Printf: %#v\n", emptyInts)
}
```

## Its output

``` go
pp.Printf: []int{}
fmt.Printf: []int(nil)
pp.Printf: []int{}
fmt.Printf: []int{}
```

**Comment by k0kubun** [comment]
Good catch. I think that should be distinguishable if possible, given that pp is used for debugging purposes. I'll take a look at fixing it tomorrow.

**Comment by k0kubun** [comment]
I think I fixed it in https://github.com/k0kubun/pp/commit/80064b0bf6a32dece73481bec12aee597d4c573b. Please try the latest master.

**Comment by xruins** [comment]
```
pp.Printf: []int(nil)
fmt.Printf: []int(nil)
pp.Printf: []int{}
fmt.Printf: []int{}
```

With latest master of https://github.com/k0kubun/pp, pp shows nil slice and empty slice distinguishably. Thanks you for quick fix and developing awesome library!
