### ISSUE TITLE
go mod doesn't install 3.0.2

### ISSUE THREAD

**Issue by a0s** [k0kubun/pp#40]
I have 
```go
import "github.com/k0kubun/pp"
```
in the main.go.  But go get (with go mod) able to install 3.0.1 only: 
```
go get
go: finding module for package github.com/k0kubun/pp
go: found github.com/k0kubun/pp in github.com/k0kubun/pp v3.0.1+incompatible
```
Could you please provide support for go mod ? I want to use 3.0.2 seamless

UPD
When using sha of the latest release:
```
go get github.com/k0kubun/pp@f5c257df338e921f81bfe022aba3d9ba2e00b7b4
go: github.com/k0kubun/pp f5c257df338e921f81bfe022aba3d9ba2e00b7b4 => v1.3.1-0.20200505181502-f5c257df338e
go: downloading github.com/k0kubun/pp v1.3.1-0.20200505181502-f5c257df338e
```
v1.3.1, what?

**Comment by k0kubun** [comment]
I think I fixed it at https://github.com/k0kubun/pp/commit/779f332785ad9842e3a90c2c020ae68135693d28. Please try `import "github.com/k0kubun/pp/v3"`.
