### ISSUE TITLE
test failed if Golang over 1.4

### ISSUE THREAD

**Issue by walf443** [k0kubun/pp#5]
SEE: https://travis-ci.org/walf443/pp/builds/46443280

**Comment by walf443** [comment]
It seems to crash on printer_test.go line 82:

```
    checkCases = []interface{}{
        map[string]int{"hell": 23, "world": 34},
        map[string]map[string]string{"s1": map[string]string{"v1": "m1", "va1": "me1"}, "si2": map[string]string{"v2": "m2"}},
        Foo{Bar: 1, Hoge: "a", Hello: map[string]string{"hel": "world", "a": "b"}, HogeHoges: []HogeHoge{HogeHoge{Hell: "a", World: 1}, HogeHoge{Hell: "bbb", World: 100}}},
        arr,
        []string{"aaa", "bbb", "ccc"},
        make(chan bool, 10),
        unsafe.Pointer(uintptr(1)),
        func(a string, b float32) int { return 0 },
        &HogeHoge{},
        &Piyo{Field1: map[string]string{"a": "b", "cc": "dd"}, F2: &Foo{}, Fie3: 128},
        []interface{}{1, 3},
        interface{}(1),
        HogeHoge{A: "test"},
        FooPri{Public: "hello", private: "world"},
        new(regexp.Regexp), // THIS LINE
    }
```

**Comment by walf443** [comment]
hmm. it seems to be Golang's bug. SEE https://github.com/golang/go/issues/9384

**Comment by k0kubun** [comment]
Thank you for your report!

> hmm. it seems to be Golang's bug. SEE golang/go#9384

I see. I commited a workaround in https://github.com/k0kubun/pp/commit/cdb03a4b2b0c943b53dc4c5ad9dac4e780c5978e. Now CI passes.

**Comment by k0kubun** [comment]
In my current understanding, `uintptr(1)` means a pointer whose address is 0x00000001.
Because it is an invalid address, conversion to unsafe.Pointer crashes.

So I changed to cast a pointer of a real struct to unsafe.Pointer. https://github.com/k0kubun/pp/commit/bbb232f7532a6033ef0068aa615d9fe08e022897

**Comment by walf443** [comment]
I see. thanks.
