### ISSUE TITLE
The color part of vim is messy

### ISSUE THREAD

**Issue by wjlzr** [k0kubun/pp#52]
The printing structure in VIM is shown in the figure
![Lark20210215-105215](https://user-images.githubusercontent.com/21358614/107900416-e9da7200-6f7b-11eb-886a-48092de28835.png)

**Comment by k0kubun** [comment]
Sorry, I'm a Vim user but I don't know what you're doing. Could you tell us steps to reproduce your problem?

**Comment by wjlzr** [comment]
I printed the structure code in VIM, but when I directly output tail - F in real time, it is normal

**Comment by wjlzr** [comment]
Garbled code

**Comment by wjlzr** [comment]
This seems to be a linux problem. I don’t know if you have a solution.

**Comment by wjlzr** [comment]
It seems that the added colors can’t be compiled and the garbled characters are displayed directly.

**Comment by k0kubun** [comment]
That's not what I'm asking. I'm a Linux user too. What I'm asking is, how did you "print the structure code in VIM"? I have simply never executed Go from Vim. Could you tell me commands or key strokes you used to reproduce this issue?

**Comment by k0kubun** [comment]
Please reopen this when you can clarify how to reproduce it.
