### ISSUE TITLE
Add option to skip unexported fields

### ISSUE THREAD

**Issue by hhhapz** [k0kubun/pp#59]
Sometimes, when printing datastructures that you don't have access to, it's not possible to modify the struct tags. In these situations, sometimes it is nice to be able to ignore **un**exported fields. Perhaps a flag on the printer, or a global variable (for the default printer) could work?

**Comment by k0kubun** [comment]
> Add option to skip unexported fields
>
> sometimes it is nice to be able to ignore exported fields

Sorry, which one do you want?

**Comment by hhhapz** [comment]
Sorry! I meant to be able to ignore _unexported_ fields, consistent with my issue title.

**Comment by k0kubun** [comment]
Could you try https://github.com/k0kubun/pp/pull/60? reflect's `IsExported()` is not available for all versions that pp supports, so I'm not sure if my implementation is right.
