### ISSUE TITLE
Please provide a simple way to disable color

### ISSUE THREAD

**Issue by jlearman** [k0kubun/pp#67]
It would be nice to have a simple way to disable all color (e.g., a function call, or option for `New()`.  The standard way is working fine, though; it's just a nuisance.

**Comment by k0kubun** [comment]
Same as https://github.com/k0kubun/pp/issues/66#issuecomment-1009596544, please show us an example code you want to use. Otherwise, this issue is not actionable for anybody besides you.

**Comment by k0kubun** [comment]
Let's reopen this after your further clarification.

**Comment by KEINOS** [comment]
@jlearman You mean something like below, don't you?

```go
package main

import (
	"fmt"

	"github.com/Code-Hex/dd"
	"github.com/k0kubun/pp/v3"
)

func main() {
	sample := []string{
		"foo",
		"bar",
	}

	pp.Println(sample)
	fmt.Println(dd.Dump(sample))
}
// Output:
// [][32mstring[0m{
//   [31m[1m"[0m[31mfoo[0m[31m[1m"[0m,
//   [31m[1m"[0m[31mbar[0m[31m[1m"[0m,
// }
// []string{
//   "foo",
//   "bar",
// }
```
- [View it online](https://go.dev/play/p/Q7bnGqASJ_J) @ Go Playground

As described in the repository description, the `pp` package is dedicated to color text printing prettily. Therefore, for CUI purposes, `pp` is nice and simple.

However, when used as a dump in print-debug or GoPlayground, I recommend to use [dd](https://github.com/Code-Hex/dd) instead. I use them both though.

**Comment by k0kubun** [comment]
> when used as a dump in print-debug

Any problem in pp for print debugging? It's the primary purpose of this library.

**Comment by KEINOS** [comment]
> @k0kubun 
> Any problem in pp for print debugging?

No. Not at all.

But the issue is "a simple way to disable all color". And the answer seemed a bit mean to me, so I wanted to provoke and ask what kind of use cases @jlearman had in mind. That's why I posted "**an example code that we want to use**" as you mentioned. That's all. 😉

Even though `pp` is great and nice for printing debug-infos "**in color**", I believe there's no **function that prints with no-color, out of the box**. Such like `dd.Dump` does. 

... ... or does it?

**Comment by k0kubun** [comment]
If we stop deprecating `pp.ColoringEnabled = false`, would you use it? 

If it doesn't work, WDYT about each of the following options?

1. `pp.WithColor(false).Println(...)`
2. `p.Println(...)` (`k0kubun/pp/p` will be a package for non-colored output)
3. `pp.Println(...)` does not colorize outputs when the destination IO is not TTY (`Sprint*` should be kept colored, or just check stdout for convenience?)

**Comment by k0kubun** [comment]
> If we stop deprecating `pp.ColoringEnabled = false`, would you use it?

As to this problem, now there's an officially blessed API: https://github.com/k0kubun/pp/releases/tag/v3.2.0

**Comment by KEINOS** [comment]
> As to this problem, now there's an officially blessed API: https://github.com/k0kubun/pp/releases/tag/v3.2.0

Wow!

```go
package main

import (
	"fmt"

	"github.com/Code-Hex/dd"
	"github.com/k0kubun/pp/v3"
)

func main() {
	sample := []string{
		"foo",
		"bar",
	}

	// pp
	{
		pp.Default.SetColoringEnabled(false)
		pp.Println(sample)
	}
	// dd
	{
		fmt.Println(dd.Dump(sample))
	}

	// Output:
	//
	// []string{
	//     "foo",
	//     "bar",
	// }
	// []string{
	//     "foo",
	//     "bar",
	// }
}
```
- [View it online](https://go.dev/play/p/VjlV6sucyV2) @ Go Playground

For my purposes this is simple and sufficient. How about you @jlearman?

@k0kubun Thank you very much! From now on, I will stick to `pp` 😉

**Comment by jlearman** [comment]
Looks great, thanks!

Sorry I never followed up on the original request.  @KEINOS is correct about what I was asking for, and I bet that `dd` would have been best for me at the time.  I had been using `pp` for other purposes and came on a new case where I didn't want color (for logging, which needed to be readable when logged to file.)
