### ISSUE TITLE
How to use the latest version?

### ISSUE THREAD

**Issue by aj3423** [k0kubun/pp#69]
I want to print numbers as decimal, but now it's hex format. I see the mater now supports a flag `p.decimalUint`, but my installed version  is: `github.com/k0kubun/pp v1.3.1-0.20200505181502-f5c257df338e`, which doesn't contain this flag, it just prints with "%#v"

I installed it via `github.com/k0kubun/pp master` in go.mod and `go mod tidy`, but why it's still different from the master?

How can I use the latest code ?

Thanks.

**Comment by k0kubun** [comment]
Because of how go mod works for v2+, you must be importing "github.com/k0kubun/pp/v3" in your code. Could you check if it did so?

(Closing the issue since it doesn't seem like pp's fault, but still I can assist in this thread as needed)
