### ISSUE TITLE
Bug?: Colorize map field names/keys using "FieldName" color scheme setting

### ISSUE THREAD

**Issue by jalavosus** [k0kubun/pp#72]
Currently, both keys and values for map types are output using the color scheme setting for "String". It would likely make a bit more sense to have field names be colorized using the "FieldName" setting.

**Comment by k0kubun** [comment]
FieldName is for structs. I don't say "field" to refer to a key of a map. First of all, the keys of maps are not necessarily "String"; they could be any type. So it makes sense to visualize what's the type of map keys by using the color for those types.

**Comment by jalavosus** [comment]
@k0kubun Unless I'm missing something, you don't actually format map keys based on their underlying types until reaching an `indentPrint` call:

- https://github.com/k0kubun/pp/blob/master/printer.go#L174
- https://github.com/k0kubun/pp/blob/master/printer.go#L179
- https://github.com/k0kubun/pp/blob/master/printer.go#L185

It would be nice to have this as a `ColorScheme` config option or something.

**Comment by jalavosus** [comment]
It would be nice to have this as a ColorScheme config option or something, is all I'm saying. At the moment, I can't find a way to _not_ have `pp` output struct names (which, for my use case, are entirely irrelevant), so being able to set the color scheme for map keys (regardless of underlying type) would be a genuinely useful feature.

**Comment by k0kubun** [comment]
> I can't find a way to not have pp output struct names

Please use `pp:"-"` https://github.com/k0kubun/pp/pull/49. Even if we didn't have the feature, converting a struct to a map and forcing key colors don't seem like a sensible way to approach it to me.
