### ISSUE TITLE
Fold large buffers

### ISSUE THREAD

**Issue by h2so5** [k0kubun/pp#8]
I want to print a struct contains a large buffer.

```go
type Foo struct {
	B [65535]byte
}

func main() {
	m := Foo{}
	pp.Print(m)
}
```

But it's not pretty and takes a long time:
```go
    ...
    ...
    ...
    0x0,
    0x0,
    0x0,
    0x0,
    0x0,
    0x0,
    0x0,
    0x0,
    0x0,
    0x0,
    ...
    ...
    ...
```

I prefer large buffers printed like this:
```go
main.Foo{
  B: [65535]uint8{...},
}
```

**Comment by k0kubun** [comment]
I agree. Your example seems nice.

If we have API to change its threshold, it'll be better.

```go
func init () {
  pp.SetBufferLimit(1028)
}
```

**Comment by k0kubun** [comment]
By the way, what was your usecase of pretty printing an object that contains such a large buffer?
I want to implement this feature considering a real usecase.
